from tkinter import *

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600

CANVAS_WIDTH = 920
CANVAS_HEIGHT = 500
CANVAS_REL_X = 0.03
CANVAS_REL_Y = 0.02

MATCH_INDENT_X = 100
MATCH_INDENT_Y = -50

INDENT_BETWEEN_MATCHES = 130
MATCH_WIDTH = 15

FIELD_POWER = 3

GAME_FRAME_BG = "cyan"

LEVEL_STORAGE = "data/levels.json"

FULL_BOARD = [1 for i in range(42)]


GAME_TITLE = "Don't play with fire v0.05"
